version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    profiles:
      - dev
      - prod
  app:
    build:
      context: .
      target: ${TARGET:-builder}
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - API_BASE_URL=https://jsonplaceholder.typicode.com
      - NODE_ENV=${NODE_ENV:-development}
    command: yarn ${COMMAND:-dev}
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    profiles:
      - dev
      - prod
volumes:
  redis_data: